package com.canerture.periodictableapp.util

import com.canerture.periodictableapp.adapter.ElementRecyclerItem
import com.canerture.periodictableapp.R

object ElementUtil {

    fun drawElementColumns(): ArrayList<Any> {

        return arrayListOf(

            //Column 1
            ElementRecyclerItem.Column(1),
            ElementRecyclerItem.Element(
                1,
                "H",
                "Hydrogen",
                "1.008",
                "1s1",
                "https://www.thoughtco.com/thmb/UugonDiouh2uSHjHo7O9pzmkikM=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/crabnebula-57e1baaa3df78c9cce3394a6.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                3,
                "Li",
                "Lithium",
                "6.94",
                "[He] 2s1",
                "https://www.thoughtco.com/thmb/VXge_ok_E_jO2wSnVzSOad6vtLI=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lithium_element-58b5e41f5f9b586046ff360e.jpg",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Element(
                11,
                "Na",
                "Sodium",
                "22.989769282",
                "[Ne] 3s1",
                "https://www.thoughtco.com/thmb/DJC9m_4zsrVPHtAXBqbA_SHUDCQ=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/sodiummetal-58b5b3c43df78cdcd8ae6517.jpg",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Element(
                19,
                "K",
                "Potassium",
                "39.09831",
                "[Ar] 4s1",
                "https://www.thoughtco.com/thmb/xOunVz8aAvU4kPGQ3I-g9BphFrY=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/81992232-58b5e3b45f9b586046fdf21a.jpg",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Element(
                37,
                "Rb",
                "Rubidium",
                "85.46783",
                "[Kr] 5s1",
                "https://www.thoughtco.com/thmb/2AmFBbMqRTQFsXRjTxKhY5N7Nk8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/rubidium-58b5e3313df78cdcd8ed1ab0.jpg",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Element(
                55,
                "Cs",
                "Cesium",
                "132.905451966",
                "[Xe] 6s1",
                "",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Element(
                87,
                "Fr",
                "Francium",
                "223",
                "[Rn] 7s1",
                "",
                R.color.alkalinemetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                0,
                "", "",
                "", "",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "",
                "",
                "",
                "",
                "",
                R.color.alkalineearthmetal,
                false
            ),

            //Column 2
            ElementRecyclerItem.Column(2),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                4,
                "Be",
                "Beryllium",
                "9.01218315",
                "[He] 2s2",
                "https://www.thoughtco.com/thmb/8sejT7WzmLM9fUrYEe5xzh77_s0=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/chinese-folding-glasses-with-beryllium-lenses-china-mid-18th-century-530024911-58b5e4183df78cdcd8efebb7.jpg",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Element(
                12,
                "Mg",
                "Magnesium",
                "24.305",
                "[Ne] 3s2",
                "https://www.thoughtco.com/thmb/Ef4t1lWaHe6tJQGx3e8JW7a0DPA=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/magnesium-58b5b3ba5f9b586046bd6f0f.jpg",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Element(
                20,
                "Ca",
                "Calcium",
                "40.0784",
                "[Ar] 4s2",
                "https://www.thoughtco.com/thmb/otWzZNYg2RcWn50gvHKTCSXclxw=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Calcium_1-58b5b3e53df78cdcd8aebde8.jpg",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Element(
                38,
                "Sr",
                "Strontium",
                "87.621",
                "[Kr] 5s2",
                "https://www.thoughtco.com/thmb/CshZpD7NGe0AcFYV53RdEDO1eJ8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Strontium_destilled_crystals-58b5e3275f9b586046fc39db.jpg",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Element(
                56,
                "Ba",
                "Barium",
                "137.3277",
                "[Xe] 6s2",
                "",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Element(
                88,
                "Ra",
                "Radium",
                "226",
                "[Rn] 7s2",
                "",
                R.color.alkalineearthmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(0, "", "", "", "", "", R.color.alkalineearthmetal, false),
            ElementRecyclerItem.Element(0, "", "", "", "", "", R.color.alkalineearthmetal, false),

            //Column 3
            ElementRecyclerItem.Column(3),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                21,
                "Sc",
                "Scandium",
                "44.9559085",
                "[Ar] 3d1 4s2",
                "https://www.thoughtco.com/thmb/pb7f5Vo_bQ0WZCnwn1kfO2gdBKY=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Scandium_sublimed_dendritic_and_1cm3_cube-58b5e3a63df78cdcd8ee910f.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                39,
                "Y",
                "Yttrium",
                "88.905842",
                "[Kr] 4d1 5s2",
                "https://www.thoughtco.com/thmb/ckrBJixk111Z-d3d_YXYgjKNNYc=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/yttrium-dendrites-cube-58b5e31c3df78cdcd8ecd911.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),

            //Column 4
            ElementRecyclerItem.Column(4),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                22,
                "Ti",
                "Titanium",
                "47.8671",
                "[Ar] 3d2 4s2",
                "https://www.thoughtco.com/thmb/LO1dWXwYr3bFY-6Hrp_BjDU-bU8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/titanium-crystals-58b5e39b3df78cdcd8ee6b67.JPG",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                40,
                "Zr",
                "Zirconium",
                "91.2242",
                "[Kr] 4d2 5s2",
                "https://www.thoughtco.com/thmb/rY6_ZWhxFaibMj31Xpd29qaMK4A=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/zicronium-crystals-cube-58b5e3185f9b586046fc0c84.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                72,
                "Hf",
                "Hafnium",
                "178.492",
                "[Xe] 4f14 5d2 6s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                104,
                "Rf",
                "Rutherfordium",
                "267",
                "[Rn] 5f14 6d2 7s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                57,
                "La",
                "Lanthanum",
                "138.905477",
                "[Xe] 5d16s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                89,
                "Ac",
                "Actinium",
                "227",
                "[Rn] 6d1 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 5
            ElementRecyclerItem.Column(5),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                23,
                "V",
                "Vanadium",
                "50.94151",
                "[Ar] 3d3 4s2",
                "https://www.thoughtco.com/thmb/pDnNck9oa0uTzXSDjBF36ma15UE=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1024px-Vanadium_crystal_bar_and_1cm3_cube-58b5e3915f9b586046fd8449.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                41,
                "Nb",
                "Niobium",
                "92.906372",
                "[Kr] 4d4 5s1",
                "https://www.thoughtco.com/thmb/Ued8U7Z7cLAG6VyZpvCkrBsGDVE=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/niobium-crystals-cube-58b5e3155f9b586046fc01d0.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                73,
                "Ta",
                "Tantalum",
                "180.947882",
                "[Xe] 4f14 5d3 6s2",
                "https://www.thoughtco.com/thmb/ACb_J36Aje5nnT7GeBEtAlKaJaA=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tantalum-58b5e2a75f9b586046fab4d5.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                105,
                "Db",
                "Dubnium",
                "268",
                "[Rn] 5f14 6d3 7s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                58,
                "Ce",
                "Cerium",
                "140.1161",
                "[Xe] 4f1 5d1 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                90,
                "Th",
                "Thorium",
                "232.03774",
                "[Rn] 6d2 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 6
            ElementRecyclerItem.Column(6),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                24,
                "Cr",
                "Chromium",
                "51.99616",
                "[Ar] 3d5 4s1",
                "https://www.thoughtco.com/thmb/Nfp1YcLhT2epNDdnBT-mqvhBIu0=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Chromium_crystals_cube-58b5c2293df78cdcd8b9d1dc.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                42,
                "Mo",
                "Molybdenum",
                "95.951",
                "[Kr] 4d5 5s1",
                "https://www.thoughtco.com/thmb/wJ37xZm7ZzDmLcsuO3cZDq8mz4A=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/molybdenum-crystal-cube-58b5e30f5f9b586046fbf20d.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                74,
                "W",
                "Tungsten",
                "183.841",
                "[Xe] 4f14 5d4 6s2",
                "https://www.thoughtco.com/thmb/_ZB0dXcuUXlRwmQErglLJC2Cl44=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tungsten-or-wolfram-58b5e2a25f9b586046faa2aa.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                106,
                "Sg",
                "Seaborgium",
                "269",
                "[Rn] 5f14 6d4 7s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                59,
                "Pr",
                "Praseodymium",
                "140.907662",
                "[Xe] 4f3 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                91,
                "Pa",
                "Protactinium",
                "231.035882",
                "[Rn] 5f2 6d1 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 7
            ElementRecyclerItem.Column(7),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                25,
                "Mn",
                "Manganese",
                "54.9380443",
                "[Ar] 3d5 4s2",
                "https://www.thoughtco.com/thmb/LPVg1LdTA8fRC67PO84lY_T2Ses=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/man-holds-handful-of-manganese-531114326-58b5e3813df78cdcd8ee1979.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                43,
                "Tc",
                "Technetium",
                "98",
                "[Kr] 4d5 5s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                75,
                "Re",
                "Rhenium",
                "186.2071",
                "[Xe] 4f14 5d5 6s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                107,
                "Bh",
                "Bohrium",
                "270",
                "[Rn] 5f14 6d5 7s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                60,
                "Nd",
                "Neodymium",
                "144.2423",
                "[Xe] 4f4 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                92,
                "U",
                "Uranium",
                "238.028913",
                "[Rn] 5f3 6d1 7s2",
                "https://www.thoughtco.com/thmb/llHKiu_nuenykjnhOtTRzhmoGX4=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/gloved-hands-with-uranium-521872354-58b5e2663df78cdcd8eab82a.jpg",
                R.color.actinide,
                true
            ),

            //Column 8
            ElementRecyclerItem.Column(8),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                26,
                "Fe",
                "Iron",
                "55.8452",
                "[Ar] 3d6 4s2",
                "https://www.thoughtco.com/thmb/ttI-VGz24VuzP9E7L6X4s9K5MyY=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/iron-58b5c6d15f9b586046cacc06.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                44,
                "Ru",
                "Ruthenium",
                "101.072",
                "[Kr] 4d7 5s1",
                "https://www.thoughtco.com/thmb/PguazZRFFDdfk8nHHhDwOIYnP9w=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Ruthenium_crystals-58b5e3063df78cdcd8ec9650.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                76,
                "Os",
                "Osmium",
                "190.233",
                "[Xe] 4f14 5d6 6s2",
                "https://www.thoughtco.com/thmb/nxPR87-s0rErXfZANrzK1xxMDJw=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/osmium-crystals-58b5e2995f9b586046fa8646.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                108,
                "Hs",
                "Hassium",
                ",",
                "[Rn] 5f14 6d6 7s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                61,
                "Pm",
                "Promethium",
                "145",
                "[Xe] 4f5 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                93,
                "Np",
                "Neptunium",
                "237",
                "[Rn] 5f4 6d1 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 9
            ElementRecyclerItem.Column(9),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                27,
                "Co",
                "Cobalt",
                "58.9331944",
                "[Ar] 3d7 4s2",
                "https://www.thoughtco.com/thmb/klav3-nF74KsbAtZQ1rsvO_PqV8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/cobalt-58b5e3753df78cdcd8edf5e0.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                45,
                "Rh",
                "Rhodium",
                "102.905502",
                "[Kr] 4d8 5s1",
                "https://www.thoughtco.com/thmb/sQWVcqLuLXl1Ubt88Y38QhBqQu4=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Rhodium_powder_pressed_melted-58b5e3005f9b586046fbc47a.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                77,
                "Ir",
                "Iridium",
                "192.2173",
                "[Xe] 4f14 5d7 6s2",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                109,
                "Mt",
                "Meitnerium",
                "278",
                "[Rn] 5f14 6d7 7s2",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                62,
                "Sm",
                "Samarium",
                "150.362",
                "[Xe] 4f6 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                94,
                "Pu",
                "Plutonium",
                "244",
                "[Rn] 5f6 7s2",
                "https://www.thoughtco.com/thmb/c_Lsy7BTH9SRX9AuroJ3vhVtt7s=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Plutonium-58b5e25d3df78cdcd8ea9a7c.jpg",
                R.color.actinide,
                true
            ),

            //Column 10
            ElementRecyclerItem.Column(10),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                28,
                "Ni",
                "Nickel",
                "58.69344",
                "[Ar] 3d8 4s2",
                "https://www.thoughtco.com/thmb/bH0ESsCN--hB0AnFnIBErc-xg20=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/mineral-specimens-481531581-58b5e36f3df78cdcd8ede048.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                46,
                "Pd",
                "Palladium",
                "106.421",
                "[Kr] 4d10",
                "",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                78,
                "Pt",
                "Platinum",
                "195.0849",
                "[Xe] 4f14 5d9 6s1",
                "https://www.thoughtco.com/thmb/HPEdEkrv5EMEejnaQp_tI9Ay-ck=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/platinum-crystals-58b5e2953df78cdcd8eb3f22.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                110,
                "Ds",
                "Darmstadtium",
                "281",
                "[Rn] 5f14 6d9 7s1",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                63,
                "Eu",
                "Europium",
                "151.9641",
                "[Xe] 4f7 6s2",
                "https://www.thoughtco.com/thmb/I6yfcrxyQ2ISh5HXyCSRyN6BtyA=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/europium-58b5c21e5f9b586046c8f373.jpg",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                95,
                "Am",
                "Americium",
                "243",
                "[Rn] 5f7 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 11
            ElementRecyclerItem.Column(11),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                29,
                "Cu",
                "Copper",
                "63.5463",
                "[Ar] 3d10 4s1",
                "https://www.thoughtco.com/thmb/KUehMeZFRjqby9jeZegOv1BEmCA=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/native-copper-bolivia-south-america-128068306-58b5e3663df78cdcd8edc232.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                47,
                "Ag",
                "Silver",
                "107.86822",
                "[Kr] 4d10 5s1",
                "https://www.thoughtco.com/thmb/Ut2R59YU4VNdK-OCetKnHbV06ek=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/raw-silver-crystal-98955646-58b5e2f63df78cdcd8ec64d0.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                79,
                "Au",
                "Gold",
                "mass",
                "xaassda",
                "https://www.thoughtco.com/thmb/ZeC68hWCc4dowtp1IttTCkEEDzg=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/gold-nugget-close-up-76128280-58b5e28e3df78cdcd8eb280a.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                111,
                "Rg",
                "Roentgenium",
                "282",
                "[Rn] 5f14 6d10 7s1",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                64,
                "Gd",
                "Gadolinium",
                "157.253",
                "[Xe] 4f7 5d1 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                96,
                "Cm",
                "Curium",
                "247",
                "[Rn] 5f7 6d1 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 12
            ElementRecyclerItem.Column(12),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                30,
                "Zn",
                "Zinc",
                "65.382",
                "[Ar] 3d10 4s2",
                "https://www.thoughtco.com/thmb/eg28LHX_zKQ_Ey83zaMnkzFlhLk=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/zinc-mine-nugget-155360569-58b5e35e5f9b586046fce53e.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                48,
                "Cd",
                "Cadmium",
                "112.4144",
                "[Kr] 4d10 5s2",
                "https://www.thoughtco.com/thmb/ttlYz5CAFebK0LZgnea5hkGtuTk=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Cadmium-crystal_bar-58b5e2ea5f9b586046fb7f9a.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                80,
                "Hg",
                "Mercury",
                "200.5923",
                "[Xe] 4f14 5d10 6s2",
                "https://www.thoughtco.com/thmb/halARGD_mLjL5EaX9lP8qriBONY=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/droplets-of-liquid-mercury-on-round-glass-tray-close-up-72002409-58b5e2825f9b586046fa3f36.jpg",
                R.color.transitionmetal,
                true
            ),
            ElementRecyclerItem.Element(
                112,
                "Cn",
                "Copernicium",
                "285",
                "[Rn] 5f14 6d10 7s2",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                65,
                "Tb",
                "Terbium",
                "158.925352",
                "[Xe] 4f9 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                97,
                "Bk",
                "Berkelium",
                "247",
                "[Rn] 5f9 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 13
            ElementRecyclerItem.Column(13),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                5,
                "B",
                "Boron",
                "10.81",
                "[He] 2s2 2p1",
                "https://www.thoughtco.com/thmb/E4TK2q8iz-sIeijIOqpeHKH-g80=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Boron_R105-58b5e4113df78cdcd8efd42e.jpg",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                13,
                "Al",
                "Aluminium",
                "26.98153857",
                "[Ne] 3s2 3p1",
                "https://www.thoughtco.com/thmb/fjaIqYqGKf8aFNO8cNuSKBciqE8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/72892858-58b5e3e15f9b586046fe7ece.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                31,
                "Ga",
                "Gallium",
                "69.7231",
                "[Ar] 3d10 4s2 4p1",
                "https://www.thoughtco.com/thmb/zL3VD7r0RurrJflKy_NKNgHu1Q8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/gallium-58b5e3573df78cdcd8ed93e0.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                49,
                "In",
                "Indium",
                "114.8181",
                "[Kr] 4d10 5s2 5p1",
                "https://www.thoughtco.com/thmb/tz4O0OcIBGLBj27DXysv1IfLLqo=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Indium-58b5c2195f9b586046c8f349.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                81,
                "Tl",
                "Thallium",
                "204.38",
                "[Xe] 4f14 5d10 6s2 6p1",
                "https://www.thoughtco.com/thmb/_86ghn0jkiX-2BtoAUtSo8Sm5bs=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Thulium_sublimed_dendritic_and_1cm3_cube-58b5e2bd5f9b586046faf5ea.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                113,
                "Nh",
                "Nihonium",
                "286",
                "[Rn] 5f14 6d10 7s2 7p1",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                66,
                "Dy",
                "Dysprosium",
                "162.5001",
                "[Xe] 4f10 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                98,
                "Cf",
                "Californium",
                "251",
                "[Rn] 5f10 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 14
            ElementRecyclerItem.Column(14),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                6,
                "C",
                "Carbon",
                "mass",
                "[He] 2s2 2p2",
                "https://www.thoughtco.com/thmb/TR2hB9_1s_jvPityinfgT0uCVLo=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/forms-of-carbon-including-a-coal-charcoal-graphite-and-diamonds-76128281-58b5e4093df78cdcd8efbbf0.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                14,
                "Si",
                "Silicon",
                "28.085",
                "[Ne] 3s2 3p2",
                "https://www.thoughtco.com/thmb/RGlJXrYvTQLdqWh41H6mYbkTsA8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/silicon-58b5e3d95f9b586046fe63cc.jpg",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                32,
                "Ge",
                "Germanium",
                "72.6308",
                "[Ar] 3d10 4s2 4p2",
                "https://www.thoughtco.com/thmb/pm7QTLmy2-MoCgfEXwGvLbGEThM=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/germanium-58b5e3543df78cdcd8ed87f2.jpg",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                50,
                "Sn",
                "Tin",
                "118.7107",
                "[Kr] 4d10 5s2 5p2",
                "https://www.thoughtco.com/thmb/ZG9YpWpo09by8mTPQQgRNbehmVo=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Sn-Alpha-Beta-58b5e2db5f9b586046fb519f.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                82,
                "Pb",
                "Lead",
                "207.21",
                "[Xe] 4f14 5d10 6s2 6p2",
                "https://www.thoughtco.com/thmb/yKKHZOZvR7JMCWldbuamVTecahI=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/lead-metal-58b5e2723df78cdcd8ead8e8.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                114,
                "Fl",
                "Flerovium",
                "289",
                "[Rn] 5f14 6d10 7s2 7p2",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                67,
                "Ho",
                "Holmium",
                "164.930332",
                "[Xe] 4f11 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                99,
                "Es",
                "Einsteinium",
                "252",
                "[Rn] 5f11 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 15
            ElementRecyclerItem.Column(15),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                7,
                "N",
                "Nitrogen",
                "14.007",
                "[He] 2s2 2p3",
                "https://www.thoughtco.com/thmb/kAzn_xU5dNBSQorciBM735Paqnk=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/nitrogen-glow-58b5dcab5f9b586046ea0671.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                15,
                "Pt",
                "Phosphorus",
                "30.9737619985",
                "[Ne] 3s2 3p3",
                "https://www.thoughtco.com/thmb/iQ1Y343LsFxfSrnIuTNnQ-PYqCE=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/phosphorus_allotropes-58b5dc9c3df78cdcd8da9840.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                33,
                "As",
                "Arsenic",
                "74.9215956",
                "[Ar] 3d10 4s2 4p3",
                "https://www.thoughtco.com/thmb/XgAHrkRhlBA4KB6mlNci3mK5nhQ=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/arsenic-75375793-58b5e34e5f9b586046fcb38b.jpg",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                51,
                "Sb",
                "Antimony",
                "121.7601",
                "[Kr] 4d10 5s2 5p3",
                "",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                83,
                "Bi",
                "Bismuth",
                "208.980401",
                "[Xe] 4f14 5d10 6s2 6p3",
                "https://www.thoughtco.com/thmb/EyAnAiwEYvO7uiKLbTWeDAohWFs=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/really-and-pure-chemical-elements-here-shown-bismuth-bi-173234101-58b5e26e3df78cdcd8eacbac.jpg",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                115,
                "Mc",
                "Moscovium",
                "289",
                "[Rn] 5f14 6d10 7s2 7p3",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                68,
                "Er",
                "Erbium",
                "167.2593",
                "[Xe] 4f12 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                100,
                "Fm",
                "Fermium",
                "257",
                "[Rn] 5f12 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 16
            ElementRecyclerItem.Column(16),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                8,
                "O",
                "Oxygen",
                "15.999",
                "[He] 2s2 2p4",
                "https://www.thoughtco.com/thmb/kgoc9-Hg0UP4XaH5zge9oLdV4sQ=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/oxygen-58b5b3b25f9b586046bd59e3.gif",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                16,
                "S",
                "Sulfur",
                "32.06",
                "[Ne] 3s2 3p4",
                "https://www.thoughtco.com/thmb/w7CZpkyxCN8kCJNQZxC2Ba6F0iM=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/close-up-of-sulphur-73685364-58b5e3ce3df78cdcd8ef0cf0.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                34,
                "Se",
                "Selenium",
                "78.9718",
                "[Ar] 3d10 4s2 4p4",
                "https://www.thoughtco.com/thmb/_rvUfOHTk5kK6vqLxIpZxAdhA5c=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/selenium-58b5e3455f9b586046fc92c1.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                52,
                "Te",
                "Tellurium",
                "127.603",
                "[Kr] 4d10 5s2 5p4",
                "https://www.thoughtco.com/thmb/SR-WeWdlY5q7pRd1tGKAMqLmKYk=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Tellurium2-58b5e2d65f9b586046fb416a.jpg",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                84,
                "Po",
                "Polonium",
                "209",
                "[Xe] 4f14 5d10 6s2 6p4",
                "",
                R.color.weakmetal,
                true
            ),
            ElementRecyclerItem.Element(
                116,
                "Lv",
                "Livermorium",
                "293",
                "[Rn] 5f14 6d10 7s2 7p4",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                69,
                "Tm",
                "Thulium",
                "168.934222",
                "[Xe] 4f13 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                101,
                "Md",
                "Mendelevium",
                "258",
                "[Rn] 5f13 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 17
            ElementRecyclerItem.Column(17),
            ElementRecyclerItem.Element(
                0,
                "Pt",
                "Platinum",
                "mass",
                "xaassda",
                "",
                R.color.alkalineearthmetal,
                false
            ),
            ElementRecyclerItem.Element(
                9,
                "F",
                "Fluorine",
                "18.9984031636",
                "[He] 2s2 2p5",
                "https://www.thoughtco.com/thmb/mxM8R0oG957N2HIUQBGRB4qIAa8=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Liquid_fluorine_tighter_crop-58b5e3f73df78cdcd8ef869d.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                17,
                "Cl",
                "Chlorine",
                "35.45",
                "[Ne] 3s2 3p5",
                "https://www.thoughtco.com/thmb/3uohA9Qa4hcsV6f2l1IKeug-F9U=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/test-tube-of-chlorine-condensed-into-liquid-by-dipping-into-jug-of-dry-ice-83189284-58b5e3c33df78cdcd8eeeb53.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                35,
                "Br",
                "Bromine",
                "79.904",
                "[Ar] 3d10 4s2 4p5",
                "https://www.thoughtco.com/thmb/Cm1GlmoVq8y8liDiNAdnucsw4q4=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Bromine-58b5e3405f9b586046fc83d4.jpg",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                53,
                "I",
                "Iodine",
                "126.904473",
                "[Kr] 4d10 5s2 5p5",
                "",
                R.color.othernonmetallic,
                true
            ),
            ElementRecyclerItem.Element(
                85,
                "At",
                "Astatine",
                "At",
                "[Xe] 4f14 5d10 6s2 6p5",
                "",
                R.color.semimetal,
                true
            ),
            ElementRecyclerItem.Element(
                117,
                "Ts",
                "Tennessine",
                "294",
                "[Rn] 5f14 6d10 7s2 7p5\"",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                70,
                "Yb",
                "Ytterbium",
                "173.0451",
                "[Xe] 4f14 6s2",
                "",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                102,
                "No",
                "Nobelium",
                "259",
                "[Rn] 5f14 7s2",
                "",
                R.color.actinide,
                true
            ),

            //Column 18
            ElementRecyclerItem.Column(18),
            ElementRecyclerItem.Element(
                2,
                "He",
                "Helium",
                "4.0026022",
                "1s2",
                "https://www.thoughtco.com/thmb/PkJimQ_mpPbIBNCYkGM0shlrhOc=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/2_Helium-liquid-58b5e4235f9b586046ff4121.png",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                10,
                "Ne",
                "Neon",
                "20.17976",
                "[He] 2s2 2p6",
                "https://www.thoughtco.com/thmb/yy0Z47RF3W-AootTL6xs5t_XL6A=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Neon-glow-58b5e2333df78cdcd8ea1954.jpg",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                18,
                "Ar",
                "Argon",
                "39.9481",
                "[Ne] 3s2 3p6",
                "https://www.thoughtco.com/thmb/-v3vBBfxXBC8iLZuwviOUAC0X-s=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/argonice-58b44b6c5f9b586046e57c02.jpg",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                36,
                "Kr",
                "Krypton",
                "83.7982",
                "[Ar] 3d10 4s2 4p6",
                "https://www.thoughtco.com/thmb/ypXO_dKLSbPOlI-Kw1ubKWPDuv4=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Krypton_discharge_tube-58b5e3393df78cdcd8ed314b.jpg",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                54,
                "Xe",
                "Xenon",
                "131.2936",
                "[Kr] 4d10 5s2 5p6",
                "https://www.thoughtco.com/thmb/0Ir4emPW5iDqOB0nJ-3F60Le4Dw=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/liquefied_xenon-58b5e2c95f9b586046fb1ab0.JPG",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                86,
                "Pt",
                "Radon",
                "222",
                "[Xe] 4f14 5d10 6s2 6p6",
                "",
                R.color.noblegas,
                true
            ),
            ElementRecyclerItem.Element(
                118,
                "Og",
                "Oganesson",
                "294",
                "[Rn] 5f14 6d10 7s2 7p6",
                "",
                R.color.na,
                true
            ),
            ElementRecyclerItem.Column(),
            ElementRecyclerItem.Element(
                71,
                "Lu",
                "Lutetium",
                "174.96681",
                "[Xe] 4f14 5d1 6s2",
                "https://www.thoughtco.com/thmb/6ipwdaqiByQUM5BIuBuWPgxjgLg=/774x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lutetium_sublimed_dendritic_and_1cm3_cube-58b5e2b15f9b586046fad099.jpg",
                R.color.lanthanide,
                true
            ),
            ElementRecyclerItem.Element(
                103,
                "Lr",
                "Lawrencium",
                "266",
                "[Rn] 5f14 7s2 7p1",
                "",
                R.color.actinide,
                true
            )
        )
    }


}